### PR TITLE
changed www to a jsfile and added start and pre start scripts to make initialization easier

### PR DESCRIPTION
**Pull request by prahaladbelavadi**

### CODE REVIEW

**Comment by prahaladbelavadi** [comment]
extension of #31

**Comment by anders94** [comment]
The pre and post start stuff is interesting, the rest (port change, the change of the name of the executable and adding you as a maintainer) isn't the direction I want to go with this. Happy to merge if you correct those things.

**Comment by prahaladbelavadi** [comment]
Hey @anders94 
I've reverted the maintainers back to the original version and changed the port back to 3000.
Running the node server requires a .js file 
I'll look into nodejs and docker integration to see if we can improve

**Comment by prahaladbelavadi** [comment]
I found this on [Docker-Nodejs webapp](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/)

**Comment by prahaladbelavadi** [comment]
I tried remodifying binary to work with nodejs and instantiate the docker image but it fails to run
I shall try executing the binary from the package.json file itself
In the meantime, we can leave it as it is until we find a better alternative

My reference list:
- [Docker practice](https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md)
- [Docker run](https://docs.docker.com/engine/reference/commandline/run/)
- [Running bin executable:feature req](https://github.com/npm/npm/issues/7137)

**Comment by prahaladbelavadi** [comment]
[This article](https://blog.jayway.com/2014/03/28/running-scripts-with-npm/) talks abouts running binaries from inside the node_modules folder, what are your thoughts on that ? @anders94

**Comment by anders94** [comment]
Sorry, slowly catching up on this - I'm guessing from one of the other issues that "Running the node server requires a .js file" is true of Windows - is that the case?

**Comment by prahaladbelavadi** [comment]
It could be a possibility
I've previously ran into similar setup issues on windows with running docker files although I think it could be because of my unfamiliarity in executing binary files.
Closing this issue as 6b8abf4624c36a0106555de279869fdab6602561 and https://github.com/anders94/blockchain-demo/commit/a2a8d17553664e4cdcab2b354ae4a29e2f2668f4 achieves the same state in a simpler fashion

I learnt quite a bit by researching about docker, binary files and its usage with npm through this
Thanks @anders94

**Pull request closed without merging**
