### PR TITLE
input type numbers, hint for 2nd Demo + basic German translations

### PR DESCRIPTION
**Pull request by rolandguelle**

### CODE REVIEW

**Comment by anders94** [comment]
I don't want to change `onkeyup` to `onchange` because I want to recalculate "as you type" while focus remains in the text field. As far as I know, `onchange` fires only after focus leaves the input.

**Comment by rolandguelle** [comment]
+1, changed.

The onchange is needed for the top / down elements rendered by (google chrome) browser.

**Comment by anders94** [comment]
What do you mean "top / down elements"? Not following...

**Comment by rolandguelle** [comment]
image

**Comment by anders94** [comment]
Aah - now I'm following. Thanks for fixing this.

**Pull request merged**
