### PR TITLE
Hungarian localization

### PR DESCRIPTION
**Pull request by DaWe35**

### CODE REVIEW

**Comment by anders94** [comment]
Hi, thanks for this. Can you remove your `package-lock.json` and update your `app.js` to the latest?

**Comment by DaWe35** [comment]
> 
> 
> Hi, thanks for this. Can you remove your `package-lock.json` and update your `app.js` to the latest?

Done :)

**Comment by anders94** [comment]
Sorry, I misspoke - can you remove your `package.json` and `package-lock.json` changes from this PR so it is only `app.js` and `locales/hu.json` that are being changed? (I notice you also fixed up `locales/en.json` but I'll let that slide. ;)

**Comment by DaWe35** [comment]
Okay sorry, is it ok now?

**Comment by anders94** [comment]
Looks perfect - thanks for the quick fixes!

**Comment by DaWe35** [comment]
When changes will be applied to the live page? Can you please notify me? Thank you :)

**Comment by anders94** [comment]
You mean the pages on https://anders.com/blockchain?

**Comment by DaWe35** [comment]
Yes of course. I want to write an article to https://www.bitcoinbazis.hu about this site.

**Comment by anders94** [comment]
OK, thanks. I'll roll it out and let you know.

**Comment by anders94** [comment]
So thinking through this a bit more, I serve https://anders.com/blockchain/ from static HTML files. To properly support i18n, I need to serve the content dynamically. This will take me a little bit more time to set up but should be doable. I'll let you know when I get that done.

**Pull request merged**
